### ISSUE TITLE
Running PDI plugin

### ISSUE THREAD

**Issue by PeeterSmitt** [stratebi/STPivot4#7]
After installing STPivot pluggin via Pentaho Marketplace onto PDI 8.0 and restarting PDI it gives following error.

2018/02/22 13:36:09 - Plugin type - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Error found while reading step plugin.xml file: file:///C:/data-integration/plugins/steps/stpivot4/plugin.xml
2018/02/22 13:36:09 - Plugin type - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : org.pentaho.di.core.exception.KettlePluginException: 
2018/02/22 13:36:09 - Plugin type - Unable to read plugin xml file: {0}:
2018/02/22 13:36:09 - Plugin type -  at java.lang.Thread.run (null:-1)
2018/02/22 13:36:09 - Plugin type -  at java.util.concurrent.ThreadPoolExecutor$Worker.run (null:-1)
2018/02/22 13:36:09 - Plugin type -  at java.util.concurrent.ThreadPoolExecutor.runWorker (null:-1)
2018/02/22 13:36:09 - Plugin type -  at java.util.concurrent.FutureTask.run (null:-1)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.ui.spoon.Spoon$1.call (Spoon.java:616)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.ui.spoon.Spoon$1.call (Spoon.java:624)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.core.KettleEnvironment.init (KettleEnvironment.java:79)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.core.KettleEnvironment.init (KettleEnvironment.java:98)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.core.KettleEnvironment.init (KettleEnvironment.java:136)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.core.plugins.PluginRegistry.init (PluginRegistry.java:575)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.core.plugins.PluginRegistry.init (PluginRegistry.java:608)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.core.plugins.PluginRegistry.registerType (PluginRegistry.java:636)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.core.plugins.BasePluginType.searchPlugins (BasePluginType.java:121)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.core.plugins.StepPluginType.registerXmlPlugins (StepPluginType.java:158)
2018/02/22 13:36:09 - Plugin type -  at org.pentaho.di.core.plugins.BasePluginType.registerPluginFromXmlResource (BasePluginType.java:415)
2018/02/22 13:36:09 - Plugin type - 
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.plugins.BasePluginType.registerPluginFromXmlResource(BasePluginType.java:422)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.plugins.StepPluginType.registerXmlPlugins(StepPluginType.java:158)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.plugins.BasePluginType.searchPlugins(BasePluginType.java:121)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.plugins.PluginRegistry.registerType(PluginRegistry.java:636)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:608)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.plugins.PluginRegistry.init(PluginRegistry.java:575)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:136)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:98)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.KettleEnvironment.init(KettleEnvironment.java:79)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.ui.spoon.Spoon$1.call(Spoon.java:624)
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.ui.spoon.Spoon$1.call(Spoon.java:616)
2018/02/22 13:36:09 - Plugin type - 	at java.util.concurrent.FutureTask.run(Unknown Source)
2018/02/22 13:36:09 - Plugin type - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2018/02/22 13:36:09 - Plugin type - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2018/02/22 13:36:09 - Plugin type - 	at java.lang.Thread.run(Unknown Source)
2018/02/22 13:36:09 - Plugin type - Caused by: java.lang.NullPointerException
2018/02/22 13:36:09 - Plugin type - 	at org.pentaho.di.core.plugins.BasePluginType.registerPluginFromXmlResource(BasePluginType.java:415)
2018/02/22 13:36:09 - Plugin type - 	... 14 more

**Comment by juancash** [comment]
Hi, I want test the plugin but I don't see into the marketplace.
